spring:
  application:
    name: master-spring-boot-2026

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/master-spring-boot-2026?createDatabaseIfNotExist=true
    username: root
    password: s0902#@!zA

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8888
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%clr([%d{yyyy-MM-dd HH:mm:ss}]){blue} %clr(%level) %clr(%msg){cyan}%n"

jwt:
  secret: "0zVgYBFLebqOD+OiK4r7HmMWB/Rzo1GQwan+5bQ+vcdk4RWyt8hCFUpFjjZTRtWDE0a6VDdCHHU9524CxI1/IA=="