spring:
  application:
    name: master-spring-boot-2026

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/master-spring-boot-2026?createDatabaseIfNotExist=true
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8888
  servlet:
    context-path: /api/v1

logging:
  pattern:
    console: "%clr([%d{yyyy-MM-dd HH:mm:ss}]){blue} %clr(%level) %clr(%msg){cyan}%n"